### ISSUE TITLE
Eclipse Temurin 17 breaks ARM32/v7 support

### ISSUE THREAD

**Issue by easimon** [easimon/shelly-exporter#1]
The Docker image is based on [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin), and the complete build is using 
docker.

- `eclipse-temurin:11` works on `linux/arm/v7`, `linux/arm64/v8` and `linux/amd64`
- `eclipse-temurin:17` works on `linux/arm64/v8` and `linux/amd64` only

With `eclipse-temurin:17`, the build (actually every `./mvnw` command) fails on the `linux/arm/v7` platform, with an error message similar to the one below. The runtime image `eclipse-temurin:17-jre` seems fine on all platforms. It's unclear if this is
an error in temurin, maven or the maven wrapper.

Further investigation is necessary, but this is the reason why the builder images, language level etc is still set to Java 11.

```
#18 3.157 Exception in thread "main" java.lang.ExceptionInInitializerError
#18 3.166 	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:546)
#18 3.166 	at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:511)
#18 3.167 	at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:500)
#18 3.168 	at java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:82)
#18 3.168 	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:65)
#18 3.169 	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:343)
#18 3.169 	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:556)
#18 3.170 	at java.base/java.lang.Class.forName0(Native Method)
#18 3.170 	at java.base/java.lang.Class.forName(Class.java:375)
#18 3.171 	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1933)
#18 3.171 	at java.base/java.security.Provider$Service.getDefaultConstructor(Provider.java:1964)
#18 3.172 	at java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1878)
#18 3.172 	at java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886)
#18 3.172 	at java.base/java.security.Provider$Service.newInstance(Provider.java:1861)
#18 3.175 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
#18 3.175 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
#18 3.176 	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
#18 3.176 	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
#18 3.177 	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:83)
#18 3.177 	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:336)
#18 3.178 	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
#18 3.178 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:81)
#18 3.178 	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
#18 3.179 	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
#18 3.179 	at java.base/java.net.URL.openConnection(URL.java:1094)
#18 3.179 	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:104)
#18 3.180 	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:97)
#18 3.180 	at org.apache.maven.wrapper.Installer.createDist(Installer.java:94)
#18 3.183 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:151)
#18 3.183 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
#18 3.187 Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
#18 3.188 	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:119)
#18 3.188 	... 30 more
#18 3.190 Caused by: java.lang.SecurityException: Couldn't iterate through the jurisdiction policy files: unlimited
#18 3.191 	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:372)
#18 3.191 	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:110)
#18 3.193 	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:107)
#18 3.194 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
#18 3.194 	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:106)
#18 3.194 	... 30 more
```

**Comment by easimon** [comment]
Tracked upstream at https://github.com/adoptium/temurin-build/issues/3094

**Comment by easimon** [comment]
Solved by building the jar on native $BUILDPLATFORM, and just packaging the final image to platform-specific variants.
