### ISSUE TITLE
Problem with Shelly1 

### ISSUE THREAD

**Issue by stabmaster1985** [easimon/shelly-exporter#103]
Hello,

i have a problem if i integrate a shelly1 host.
i get the following error if i add it to the host list and start the docker container.

`2024-05-22T10:57:52.558Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ex-0000000014 preparing request execution
2024-05-22T10:57:52.559Z DEBUG 1 --- [   scheduling-1] o.a.h.c.http.impl.classic.ProtocolExec   : ex-0000000014 target auth state: UNCHALLENGED
2024-05-22T10:57:52.559Z DEBUG 1 --- [   scheduling-1] o.a.h.c.http.impl.classic.ProtocolExec   : ex-0000000014 proxy auth state: UNCHALLENGED
2024-05-22T10:57:52.559Z DEBUG 1 --- [   scheduling-1] o.a.h.c.http.impl.classic.ConnectExec    : ex-0000000014 acquiring connection with route {}->http://192.168.0.88:80
2024-05-22T10:57:52.559Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ex-0000000014 acquiring endpoint (3 MINUTES)
2024-05-22T10:57:52.560Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ex-0000000014 endpoint lease request (3 MINUTES) [route: {}->http://192.168.0.88:80][total available: 0; route allocated: 0 of 10; total allocated: 0 of 40]
2024-05-22T10:57:52.560Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ex-0000000014 endpoint leased [route: {}->http://192.168.0.88:80][total available: 0; route allocated: 1 of 10; total allocated: 1 of 40]
2024-05-22T10:57:52.560Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ex-0000000014 acquired ep-0000000014
2024-05-22T10:57:52.560Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ex-0000000014 acquired endpoint ep-0000000014
2024-05-22T10:57:52.560Z DEBUG 1 --- [   scheduling-1] o.a.h.c.http.impl.classic.ConnectExec    : ex-0000000014 opening connection {}->http://192.168.0.88:80
2024-05-22T10:57:52.561Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ep-0000000014 connecting endpoint (null)
2024-05-22T10:57:52.561Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ep-0000000014 connecting endpoint to http://192.168.0.88:80 (5 SECONDS)
2024-05-22T10:57:52.561Z DEBUG 1 --- [   scheduling-1] .i.i.DefaultHttpClientConnectionOperator : 192.168.0.88 resolving remote address
2024-05-22T10:57:52.561Z DEBUG 1 --- [   scheduling-1] .i.i.DefaultHttpClientConnectionOperator : 192.168.0.88 resolved to [/192.168.0.88]
2024-05-22T10:57:52.562Z DEBUG 1 --- [   scheduling-1] .i.i.DefaultHttpClientConnectionOperator : 192.168.0.88:80 connecting null->/192.168.0.88:80 (5 SECONDS)
2024-05-22T10:57:52.573Z DEBUG 1 --- [   scheduling-1] h.i.i.DefaultManagedHttpClientConnection : http-outgoing-13 set socket timeout to 5 SECONDS
2024-05-22T10:57:52.573Z DEBUG 1 --- [   scheduling-1] .i.i.DefaultHttpClientConnectionOperator : 192.168.0.88:80 connected null->/192.168.0.88:80 as http-outgoing-13
2024-05-22T10:57:52.574Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ep-0000000014 connected http-outgoing-13
2024-05-22T10:57:52.575Z DEBUG 1 --- [   scheduling-1] h.i.i.DefaultManagedHttpClientConnection : http-outgoing-13 set socket timeout to 5 SECONDS
2024-05-22T10:57:52.575Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ep-0000000014 endpoint connected
2024-05-22T10:57:52.575Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.impl.classic.MainClientExec    : ex-0000000014 executing GET /status HTTP/1.1
2024-05-22T10:57:52.576Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ep-0000000014 start execution ex-0000000014
2024-05-22T10:57:52.576Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ep-0000000014 executing exchange ex-0000000014 over http-outgoing-13
2024-05-22T10:57:52.576Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 >> GET /status HTTP/1.1
2024-05-22T10:57:52.577Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 >> Accept: application/json, application/*+json
2024-05-22T10:57:52.577Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 >> Accept-Encoding: gzip, x-gzip, deflate
2024-05-22T10:57:52.577Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 >> Host: 192.168.0.88
2024-05-22T10:57:52.577Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 >> Connection: keep-alive
2024-05-22T10:57:52.578Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 >> User-Agent: Apache-HttpClient/5.2.3 (Java/17.0.11)
2024-05-22T10:57:52.578Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "GET /status HTTP/1.1[\r][\n]"
2024-05-22T10:57:52.578Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "Accept: application/json, application/*+json[\r][\n]"
2024-05-22T10:57:52.585Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "Accept-Encoding: gzip, x-gzip, deflate[\r][\n]"
2024-05-22T10:57:52.585Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "Host: 192.168.0.88[\r][\n]"
2024-05-22T10:57:52.586Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "Connection: keep-alive[\r][\n]"
2024-05-22T10:57:52.586Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "User-Agent: Apache-HttpClient/5.2.3 (Java/17.0.11)[\r][\n]"
2024-05-22T10:57:52.586Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 >> "[\r][\n]"
2024-05-22T10:57:52.616Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "HTTP/1.1 200 OK[\r][\n]"
2024-05-22T10:57:52.616Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "Server: Mongoose/6.18[\r][\n]"
2024-05-22T10:57:52.616Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "Connection: close[\r][\n]"
2024-05-22T10:57:52.616Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "Content-Type: application/json[\r][\n]"
2024-05-22T10:57:52.616Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "Content-Length: 844[\r][\n]"
2024-05-22T10:57:52.617Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "[\r][\n]"
2024-05-22T10:57:52.617Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.wire          : http-outgoing-13 << "{"wifi_sta":{"connected":true,"ssid":"my-WLAN","ip":"192.168.0.88","rssi":-72},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":true},"time":"12:57","unixtime":1716375473,"serial":1,"has_update":false,"mac":"123456789012","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"source":"mqtt"}],"meters":[{"power":0.00,"is_valid":true}],"inputs":[{"input":0,"event":"","event_cnt":0}],"ext_sensors":{},"ext_temperature":{},"ext_humidity":{},"update":{"status":"idle","has_update":false,"new_version":"20230913-112003/v1.14.0-gcb84623","old_version":"20230913-112003/v1.14.0-gcb84623","beta_version":"20231107-162940/v1.14.1-rc1-g0617c15"},"ram_total":51688,"ram_free":39728,"fs_size":233681,"fs_free":150349,"uptime":8775365}"
2024-05-22T10:57:52.618Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 << HTTP/1.1 200 OK
2024-05-22T10:57:52.622Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 << Server: Mongoose/6.18
2024-05-22T10:57:52.623Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 << Connection: close
2024-05-22T10:57:52.623Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 << Content-Type: application/json
2024-05-22T10:57:52.623Z DEBUG 1 --- [   scheduling-1] org.apache.hc.client5.http.headers       : http-outgoing-13 << Content-Length: 844
2024-05-22T10:57:52.628Z DEBUG 1 --- [   scheduling-1] h.i.i.DefaultManagedHttpClientConnection : http-outgoing-13 close connection IMMEDIATE
2024-05-22T10:57:52.628Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ep-0000000014 endpoint closed
2024-05-22T10:57:52.629Z DEBUG 1 --- [   scheduling-1] o.a.h.c.h.i.classic.InternalHttpClient   : ep-0000000014 discarding endpoint
2024-05-22T10:57:52.629Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ep-0000000014 releasing endpoint
2024-05-22T10:57:52.629Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ep-0000000014 connection is not kept alive
2024-05-22T10:57:52.629Z DEBUG 1 --- [   scheduling-1] h.i.i.PoolingHttpClientConnectionManager : ep-0000000014 connection released [route: {}->http://192.168.0.88:80][total available: 0; route allocated: 0 of 10; total allocated: 0 of 40]
2024-05-22T10:57:52.630Z  WARN 1 --- [   scheduling-1] c.d.s.exporter.client.ShellyGen1Client   : GET http://192.168.0.88/status: HTTP Request failure: Error while extracting response for type [class click.dobel.shelly.exporter.client.api.gen1.Status] and content type [application/json]
org.springframework.web.client.RestClientException: Error while extracting response for type [class click.dobel.shelly.exporter.client.api.gen1.Status] and content type [application/json]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:118) ~[spring-web-6.1.5.jar!/:6.1.5]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:892) ~[spring-web-6.1.5.jar!/:6.1.5]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790) ~[spring-web-6.1.5.jar!/:6.1.5]
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:404) ~[spring-web-6.1.5.jar!/:6.1.5]
	at click.dobel.shelly.exporter.client.ShellyGen1Client.status(ShellyGen1Client.kt:40) ~[!/:2.5.5]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:64) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:416) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheAspectSupport.lambda$executeSynchronized$2(CacheAspectSupport.java:454) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.caffeine.CaffeineCache$LoadFunction.apply(CaffeineCache.java:237) ~[spring-context-support-6.1.5.jar!/:6.1.5]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688) ~[caffeine-3.1.8.jar!/:3.1.8]
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[na:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686) ~[caffeine-3.1.8.jar!/:3.1.8]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669) ~[caffeine-3.1.8.jar!/:3.1.8]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[caffeine-3.1.8.jar!/:3.1.8]
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[caffeine-3.1.8.jar!/:3.1.8]
	at org.springframework.cache.caffeine.CaffeineCache.get(CaffeineCache.java:135) ~[spring-context-support-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheAspectSupport.executeSynchronized(CacheAspectSupport.java:454) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:423) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:395) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:74) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.5.jar!/:6.1.5]
	at click.dobel.shelly.exporter.client.ShellyGen1Client$$SpringCGLIB$$0.status(<generated>) ~[!/:2.5.5]
	at click.dobel.shelly.exporter.metrics.ShellyGen1Metrics.register(ShellyGen1Metrics.kt:151) ~[!/:2.5.5]
	at click.dobel.shelly.exporter.metrics.ShellyMetrics.register(ShellyMetrics.kt:28) ~[!/:2.5.5]
	at click.dobel.shelly.exporter.discovery.ShellyDeviceRegistry.updateAddresses(ShellyDeviceRegistry.kt:62) ~[!/:2.5.5]
	at click.dobel.shelly.exporter.discovery.ShellyGen1DeviceRegistry.updateAddresses(ShellyGen1DeviceRegistry.kt:39) ~[!/:2.5.5]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.5.jar!/:6.1.5]
	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.4.jar!/:1.12.4]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.5.jar!/:6.1.5]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.5.jar!/:6.1.5]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `click.dobel.shelly.exporter.client.api.gen1.Status$Meter`, problem: Parameter specified as non-null is null: method click.dobel.shelly.exporter.client.api.gen1.Status$Meter.<init>, parameter counters
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406) ~[spring-web-6.1.5.jar!/:6.1.5]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.1.5.jar!/:6.1.5]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103) ~[spring-web-6.1.5.jar!/:6.1.5]
	... 50 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `click.dobel.shelly.exporter.client.api.gen1.Status$Meter`, problem: Parameter specified as non-null is null: method click.dobel.shelly.exporter.client.api.gen1.Status$Meter.<init>, parameter counters
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 454] (through reference chain: click.dobel.shelly.exporter.client.api.gen1.Status["meters"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2058) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:598) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:621) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:301) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:525) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1419) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1419) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[spring-web-6.1.5.jar!/:6.1.5]
	... 52 common frames omitted
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method click.dobel.shelly.exporter.client.api.gen1.Status$Meter.<init>, parameter counters
	at click.dobel.shelly.exporter.client.api.gen1.Status$Meter.<init>(Status.kt) ~[!/:2.5.5]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:128) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:291) ~[jackson-databind-2.15.4.jar!/:2.15.4]
	... 71 common frames omitted`

Do you know what is wrong?

**Comment by easimon** [comment]
Hmpf, sorry, my bad -- That is what happens if I should have written a test for this case and did not.

Now, with release 2.5.7, it should go better -- optimally just work, or at least the error message should be different.
Please try again.

**Comment by stabmaster1985** [comment]
Wow ... now it work's very well. Thank you very much. Great tool :-)

One other thing ... maybe you can look at this error ... if the script run into a timeout, you get a long error message.

`2024-05-24T19:28:22.306Z  WARN 1 --- [   scheduling-1] c.d.s.exporter.client.ShellyGen1Client   : GET http://192.168.0.95/settings: HTTP Request failure: I/O error on GET request for "http://192.168.0.95/settings": Read timed out
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://192.168.0.95/settings": Read timed out
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:915) ~[spring-web-6.1.5.jar!/:6.1.5]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:895) ~[spring-web-6.1.5.jar!/:6.1.5]`

Maybe it's possible to script it out?! ;-)

**Comment by easimon** [comment]
I moved exception stack traces to the DEBUG log level, which is not logged by default. Please check version 2.5.8.

Since this is not the original problem, I am closing this issue now. But feel free to open a new one if you have other problems, feature ideas or similar.
